export const question=[
    {
        id: 1,
        question: 'Thủ đô của Việt Nam là gì?',
        a: 'Hồ Chí Minh',
        b: 'Đà Nẵng',
        c: 'Hà Nội',
        d: 'Cần Thơ',
        conrectAns: 'c',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 2,
        question: '2 + 3 bằng bao nhiêu?',
        a: '4',
        b: '5',
        c: '6',
        d: '7',
        conrectAns: 'b',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 3,
        question: 'Màu của lá cây thường là gì?',
        a: 'Đỏ',
        b: 'Vàng',
        c: 'Xanh lá',
        d: 'Tím',
        conrectAns: 'c',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 4,
        question: 'Động vật nào kêu "meo meo"?',
        a: 'Chó',
        b: 'Mèo',
        c: 'Bò',
        d: 'Vịt',
        conrectAns: 'b',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 5,
        question: 'Trái chuối thuộc loại gì?',
        a: 'Rau',
        b: 'Củ',
        c: 'Trái cây',
        d: 'Thịt',
        conrectAns: 'c',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 6,
        question: 'Một tuần có bao nhiêu ngày?',
        a: '5',
        b: '6',
        c: '7',
        d: '8',
        conrectAns: 'c',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 7,
        question: 'Việt Nam nằm ở châu lục nào?',
        a: 'Châu Âu',
        b: 'Châu Mỹ',
        c: 'Châu Á',
        d: 'Châu Phi',
        conrectAns: 'c',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 8,
        question: 'Mặt trời mọc ở hướng nào?',
        a: 'Bắc',
        b: 'Nam',
        c: 'Đông',
        d: 'Tây',
        conrectAns: 'c',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 9,
        question: 'Mùa nào có thời tiết nóng nhất trong năm?',
        a: 'Xuân',
        b: 'Hạ',
        c: 'Thu',
        d: 'Đông',
        conrectAns: 'b',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 10,
        question: '1 giờ có bao nhiêu phút?',
        a: '30 phút',
        b: '60 phút',
        c: '90 phút',
        d: '100 phút',
        conrectAns: 'b',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 11,
        question: 'Con vật nào sống dưới nước?',
        a: 'Mèo',
        b: 'Chó',
        c: 'Cá',
        d: 'Ngựa',
        conrectAns: 'c',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 12,
        question: 'Việt Nam có bao nhiêu mùa trong năm?',
        a: '2',
        b: '3',
        c: '4',
        d: '5',
        conrectAns: 'c',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 13,
        question: 'Nước là chất gì?',
        a: 'Rắn',
        b: 'Lỏng',
        c: 'Khí',
        d: 'Cứng',
        conrectAns: 'b',
        userAns: null,
        isCorrect: null,
        level: 2,
        status: true
    },
    {
        id: 14,
        question: 'Con người dùng bộ phận nào để nghe?',
        a: 'Mắt',
        b: 'Mũi',
        c: 'Miệng',
        d: 'Tai',
        conrectAns: 'd',
        userAns: null,
        isCorrect: null,
        level: 2,
        status: true
    },
    {
        id: 15,
        question: 'Chữ cái đầu tiên trong bảng chữ cái tiếng Việt là gì?',
        a: 'A',
        b: 'B',
        c: 'C',
        d: 'D',
        conrectAns: 'a',
        userAns: null,
        isCorrect: null,
        level: 2,
        status: true
    }
]

